language: clojure
addons:
  apt:
    packages:
      - docker-ce
    sources:
      - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable test'
        key_url: 'https://download.docker.com/linux/ubuntu/gpg'
cache:
  directories:
    - ~/.m2
    - ~/docker
jdk:
  - openjdk8
env:
  - DOCKER=test
  - DOCKER=stable
  - DOCKER=19.03
  - DOCKER=18.09
  - DOCKER=18.03
  - DOCKER=17.12
  - DOCKER=17.09
  - DOCKER=17.06
  - DOCKER=17.03
  - DOCKER=1.13
install:
  - sudo sysctl -w net.ipv4.tcp_mtu_probing=1
  - bash dev/script/init-db.sh
  - bash dev/script/init-influx.sh
  - bash dev/script/init-agent.sh
  - bash dev/script/start-dind.sh
script:
  - lein deps
  - lein test :all
  - bash dev/script/enable-experimental-docker.sh
  - bash dev/script/deploy-image.sh
notifications:
  slack:
    secure: N7vVeSPB1vnrMen7MJ6HKXBaIaYFoV/fU20PpnJfpzkmESEjnK8YG7dhaX+0UqWdTnc6o4RkttGLa3JOV7fKOtnRAwMf+djsWaHAfhkJjujEeTC457hKEn54IJYlRIhsNki6b+HSM/NfjHy4dx7DubeiDq7rouRUsh5apHtktCay5Z7uhqN3Hl7P6OcFOKk/tfQyEurgfLMNBF5XwIQsumsWY2WQxWwwS1lcqPqPv5ol5RzF4RG1D4B0SAWcNJTu7xYu8vQYkC/Cl3HRGvt1YeiEe8TX4TxYqszj1/JSqadmttL4lHkWOnz67/wA3slZU5cQeidtdW1OG41h8wB139cBdYnTmUaIuLgv8sKNGEU1Vn3xOG9tl3GKjZtGKB/kDyY6paJxcXBnNjQKEkoFp7pdM2DsssbkLpgOq8LK91b5xTFEoOk60MJJyiALuaDuWWCYJF7qFjwBVtv8WCiXengFF+5BiFwkk21BaoW9+PKLKlSIFSf6GLrbMxn9rUcjHqOl89lv5jGBrwp3UE0soto3w7xvmu18Dy5jBYuNAk8t+hKYypZ8sDbYVVGTO2PnDUedMgqYvDbiKJ4fXGRbbDIM76wVxiDiVeznkqJArysN/tPbJvECedWpaU7mAEvyN1q/5NX0x98SCJQA/GB0i82aov6nqmnkx0FYvtXVInM=
